using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;

namespace EnklWiki.Api.Services;

// Mirrors the client's SubtleCrypto PBKDF2 credential hashing exactly
// (src/auth/credential.js) so a salt/hash pair generated by either side is
// interchangeable: PBKDF2-SHA256, 100,000 iterations, 16-byte salt,
// 256-bit derived key, both encoded as lowercase hex.
public class CredentialService(IConfiguration configuration)
{
    private const int Iterations = 100_000;
    private const int SaltBytes = 16;
    private const int HashBytes = 32;

    public (string Salt, string Hash) HashCredential(string secret)
    {
        var salt = RandomNumberGenerator.GetBytes(SaltBytes);
        var hash = DeriveHash(secret, salt);
        return (Convert.ToHexStringLower(salt), Convert.ToHexStringLower(hash));
    }

    public bool VerifyCredential(string secret, string saltHex, string hashHex)
    {
        if (string.IsNullOrEmpty(saltHex) || string.IsNullOrEmpty(hashHex)) return false;
        var salt = Convert.FromHexString(saltHex);
        var expected = Convert.FromHexString(hashHex);
        var actual = DeriveHash(secret, salt);
        return CryptographicOperations.FixedTimeEquals(actual, expected);
    }

    private static byte[] DeriveHash(string secret, byte[] salt) =>
        Rfc2898DeriveBytes.Pbkdf2(Encoding.UTF8.GetBytes(secret), salt, Iterations, HashAlgorithmName.SHA256, HashBytes);

    public string IssueToken(string role)
    {
        var signingKey = configuration["Jwt:SigningKey"]
            ?? throw new InvalidOperationException("Jwt:SigningKey is not configured.");
        var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(signingKey));
        var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

        var token = new JwtSecurityToken(
            issuer: "enkl-wiki-api",
            audience: "enkl-wiki-client",
            claims: [new Claim(ClaimTypes.Role, role)],
            expires: DateTime.UtcNow.AddHours(12),
            signingCredentials: creds
        );

        return new JwtSecurityTokenHandler().WriteToken(token);
    }
}
